### PR TITLE
Configurable default backend

### PR DESCRIPTION
**Pull request by kjoller**
I have made the default config for this option to be ```defaultBackend: true``` in order to match current behavior.

### CODE REVIEW

**Comment by stakater-user** [comment]
@kjoller Image is available for testing. ``docker pull stakater/xposer:SNAPSHOT-PR-20-1``

**Comment by waseem-h** [comment]
@kjoller looks pretty nice. Can you add its details in the readme as well?

**Comment by stakater-user** [comment]
@kjoller Image is available for testing. ``docker pull stakater/xposer:SNAPSHOT-PR-20-2``

**Comment by kjoller** [comment]
This is not ready for merging. ```Ingress.Spec.Backend``` is used for matching an ingress to its service in ```ingresses```/```GetFromListMatchingGivenServiceName``` in, and for displaying a servicename in the controller.

I would propose to move this connection from a service with ```expose: true``` to its Xposer generated ingress to an annotation instead of matching through the Spec.Backend, as this could be missing (in my use case), or be defined in other non-xposer ingresses.

**Comment by stakater-user** [comment]
@kjoller Image is available for testing. ``docker pull stakater/xposer:SNAPSHOT-PR-20-3``

**Comment by guillermobandres** [comment]
Hi is this merged? 

Thank you

**Comment by kjoller** [comment]
Not merged, should not be merged. Consider it abandoned :-(

**Pull request closed without merging**
